### ISSUE TITLE
第一次配置实盘信息时报错详见截图

### ISSUE THREAD

**Issue by flyafly** [xbx-quant/quant-client#1]
![image](https://github.com/user-attachments/assets/9cd2ab11-6de2-46a0-8c6b-3add69c8c830)

**Comment by xbx-quant** [comment]
### 问题原因
获取 config 中时间问题，初始化异常导致
### 手动临时解决办法
1. 从右下角点击打开日志文件夹，再往上一级文件路径，找到 config.json，然后关闭客户端
2. 搜索是否有real_market_config，没有的话手动在末尾添加 
```json
"real_market_config": {
      "qmt_path": "",
      "account_id": "",
      "qmt_port": "58610",
      "message_robot_url": "",
      "filter_kcb": true,
      "filter_cyb": true,
      "performance_mode": "EQUAL",
      "date_start": "2021-12-23"
}
```
如果有，那么只需要添加 date_start 即可，然后重启客户端

**Comment by flyafly** [comment]
> ### 问题原因
> 获取 config 中时间问题，初始化异常导致
> 
> ### 手动临时解决办法
> 1. 从右下角点击打开日志文件夹，再往上一级文件路径，找到 config.json，然后关闭客户端
> 2. 搜索是否有real_market_config，没有的话手动在末尾添加
> 
> ```json
> "real_market_config": {
>       "qmt_path": "",
>       "account_id": "",
>       "qmt_port": "58610",
>       "message_robot_url": "",
>       "filter_kcb": true,
>       "filter_cyb": true,
>       "performance_mode": "EQUAL",
>       "date_start": "2021-12-23"
> }
> ```
> 
> 如果有，那么需要添加 date_start 和 qmt_port 即可，然后重启客户端

谢谢萌萌，好使了
